notifications:
    email:
        - dean@airdb.com
dist: trusty
sudo: required
services:
      - docker
language: go
go:
    - 1.8
addons:
    apt:
        package:
            - docker-ce

# cache components
before_install:
    - docker pull airdb/alpine:latest
install:
      - if [ $TRAVIS_OS_NAME = linux ]; then echo linux; else echo xxx; fi
      - curl airdb.com/install
before_script:
    - curl airdb.com/before_script
script:
    - curl airdb.com/script
after_success:
    - curl -d "msg=Auto ci success. https://travis-ci.org/airdb/docs" http://airdb.com:9090/tarvis-ci/callback
after_failure:
    - curl -d "msg=Auto ci failure. https://travis-ci.org/airdb/docs" http://airdb.com:9090/tarvis-ci/callback
before_deploy:
    - curl airdb.com/before_deploy
# deploy:
#     - curl airdb.com/deploy
after_deploy:
    - curl airdb.com/after_deploy
after_script:
    - curl airdb.com/after_scritp
