site_name: airdb
theme: readthedocs
pages:
- Overview: index.md
- 持续集成: ci.md
- 持续部署: cd.md
- 机器学习: AIAlgorithm.md
- 职业生涯: career.md
- SRE文化: sre.md
- 实践: 02_practice.md
- 公益:  forfun.md
- AIFM的想法: aifm.md
- 关于求职: jobs/salary.md
- 关于真实: dean/sincere.md
- 文档贡献: 03_how_to_github_pull_request.md
- 文档排版: 04_chinese_copywrite_guidelines.md
