site_name: airdb
theme: readthedocs
pages:
- Overview: index.md
- 开源软件: 01_opensource.md
- 实践: 02_practice.md
- 公益:  forfun.md
- 关于真实: dean/sincere.md
- 文档贡献: 03_how_to_github_pull_request.md
- 文档排版: 04_chinese_copywrite_guidelines.md
