site_name: airdb
site_description:  https://airdb.io
site_author: YiNo

repo_url: https://github.com/airdb
edit_uri: https://github.com/airdb/index

theme: Flatly

nav:
        - Home: index.md
        - User Guide: lovelytech.md

extra_css:
        - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2014 <a href="https://github.com/airdb">Dean</a>, Maintained by the YiNo Team</a>.

plugins:
    - search
